FROM golang:1.23.5 as builder

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o gateway ./part3/cmd/gateway/main.go

FROM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /app/gateway /app/

EXPOSE 8080
CMD ["/app/gateway", "-discovery", "${DISCOVERY_HOST}:${DISCOVERY_PORT}", "-port", "8080"]
