services:
  # Discovery Server (private service)
  - type: pserv
    name: discovery-server
    runtime: docker
    dockerfilePath: ./Dockerfile.discovery
    dockerContext: .
    plan: standard
    numInstances: 1
    envVars:
      - key: DISCOVERY_PORT
        value: "8000"
    buildFilter:
      paths:
        - part3/cmd/discovery/**
        - part3/discovery/**

  # Gateway Service (public)
  - type: web
    name: counter-gateway
    runtime: docker
    dockerfilePath: ./Dockerfile.gateway
    dockerContext: .
    plan: standard
    numInstances: 1
    envVars:
      - key: PORT
        value: "8080"
      - key: DISCOVERY_HOST
        fromService:
          name: discovery-server
          type: pserv
          property: host
      - key: DISCOVERY_PORT
        value: "8000"
    healthCheckPath: /health
    buildFilter:
      paths:
        - part3/cmd/gateway/**

  # Node Group 1 (private)
  - type: pserv
    name: nodes-group1
    runtime: docker
    dockerfilePath: ./Dockerfile.node
    dockerContext: .
    plan: standard
    numInstances: 1
    envVars:
      - key: NODE_START_PORT
        value: "9001"
      - key: NODE_COUNT
        value: "3"
      - key: DISCOVERY_HOST
        fromService:
          name: discovery-server
          type: pserv
          property: host
      - key: DISCOVERY_PORT
        value: "8000"
    buildFilter:
      paths:
        - part3/cmd/counter/**
        - part3/node/**
        - part3/peer/**
        - part3/protocol/**
        - part3/wal/**

  # Node Group 2 (private)
  - type: pserv
    name: nodes-group2
    runtime: docker
    dockerfilePath: ./Dockerfile.node
    dockerContext: .
    plan: standard
    numInstances: 1
    envVars:
      - key: NODE_START_PORT
        value: "9004"
      - key: NODE_COUNT
        value: "3"
      - key: DISCOVERY_HOST
        fromService:
          name: discovery-server
          type: pserv
          property: host
      - key: DISCOVERY_PORT
        value: "8000"
    buildFilter:
      paths:
        - part3/cmd/counter/**
        - part3/node/**
        - part3/peer/**
        - part3/protocol/**
        - part3/wal/**
